library/books/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views
from .views import *

app_name = "books"

urlpatterns = [
    path("", BookListView.as_view(), name="book_list"),
    path("books/new/", BookCreateView.as_view(), name="book_create"),
    path("books/<int:pk>/edit/", BookUpdateView.as_view(), name="book_update"),
    path("books/<int:pk>/delete/", views.BookDeleteView.as_view(), name="book_delete"),
    path("bulk-delete/", views.bulk_delete_books, name="bulk_delete_books"), 
    path("authors/<int:pk>/", views.AuthorDetailView.as_view(), name="author_detail"),

    path("fav/<int:pk>/", views.toggle_favorite, name="toggle_favorite"),
    path("favorites/", MyFavoritesListView.as_view(), name="my_favorites"),

]

library/library/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path("accounts/", include("accounts.urls")),

]

library/library/templates/base.html
<!doctype html>
<html lang="fa" dir="rtl">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>{% block title %}FOAD FERDOWS LIBRARY{% endblock %}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css">
  <style> body{max-width:1100px;margin:auto} .muted{opacity:.7} </style>
</head>
<body>
  <nav>
    <ul><li><strong><a href="{% url 'books:book_list' %}">Home</a></strong></li></ul>
    <ul>
      <li><a href="{% url 'books:book_create' %}">add new book +</a></li>
      {% if user.is_authenticated %}
        <li><a href="{% url 'books:my_favorites' %}">Favorites</a></li>
      {% else %}
        <li><a href="/admin/login/">Enter</a></li>
      {% endif %}
    </ul>
  </nav>
  <main>
    {% for m in messages %}<article class="contrast">{{ m }}</article>{% endfor %}
    {% block content %}{% endblock %}
  </main>
</body>
</html>